version: '3.9'

services:
  mint_db:
    image: postgres
    container_name: postgresCont
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: word
      POSTGRES_USER: anbi
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}